name: check
on: [push, pull_request]

jobs:
  publish:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'build/test-results/test/TEST-*.xml'
