name: dokka

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Build and Publish Dokka Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8

      - name: Build Docs
        uses: gradle/gradle-build-action@v2
        with:
          arguments: dokkaHtml

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build/dokka/html
